// -----------------------------------------------------------------------------
// Prepares the end-to-end tests (tests/integration.test.ts):
//   1. dumps the full data model to tests/support/dmmf.json
//   2. generates a test-only Prisma client that talks to PostgreSQL through
//      the small `pg` adapter in tests/support (no native engine needed)
// Run once after changing prisma/schema.prisma:  npm run test:prepare
// -----------------------------------------------------------------------------
import fs from "fs";
import path from "path";
import { execSync } from "child_process";

const root = process.cwd();
const schema = fs.readFileSync(path.join(root, "prisma/schema.prisma"), "utf8");
const body = schema.slice(schema.indexOf("datasource db"));
const generatorPath = path.join(root, "tests/support/dmmf-generator.cjs").replace(/\\/g, "/");

fs.writeFileSync(
  path.join(root, "tests/support/dmmf.prisma"),
  `// AUTO-GENERATED by npm run test:prepare\ngenerator dump {\n  provider = "node ${generatorPath}"\n}\n\n${body}`
);
fs.writeFileSync(
  path.join(root, "tests/support/schema.test.prisma"),
  `// AUTO-GENERATED by npm run test:prepare\ngenerator client {\n  provider        = "prisma-client-js"\n  previewFeatures = ["queryCompiler", "driverAdapters"]\n  engineType      = "client"\n  output          = "../../node_modules/.prisma-test/client"\n}\n\n${body}`
);
const env = { ...process.env, DATABASE_URL: process.env.DATABASE_URL || "postgresql://unused/unused" };
execSync("npx prisma generate --schema tests/support/dmmf.prisma", { stdio: "inherit", env });
execSync("npx prisma generate --schema tests/support/schema.test.prisma", { stdio: "inherit", env });
console.log("Test client ready. Run: npm run test:e2e");
